import java.awt.Desktop;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class OrderForm extends javax.swing.JFrame {

    ButtonGroup radPizzaSizes = new ButtonGroup();
    
    private double totalPrice = 0; //otherwise it will keep resetting itself each time you add a new item to the order.
    
    public OrderForm() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("fabulous_pizzas_icon.png")).getImage()); //new icon        
        
        txtPizzaQuantity.setText("1"); txtDrinkQuantity.setText("1"); //default quantities
        
        //all sizes in same radio button group
        radPizzaSizes.add(rad8Inch); 
        radPizzaSizes.add(rad12Inch); 
        radPizzaSizes.add(rad16Inch);
        
        quickTesting();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCustomerDetails = new javax.swing.JPanel();
        lblCustomerDetails = new javax.swing.JLabel();
        lblAddLine4 = new javax.swing.JLabel();
        txtAddLine4 = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        lblContactNumber = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtContactNumber = new javax.swing.JTextField();
        lblAddLine1 = new javax.swing.JLabel();
        txtAddLine1 = new javax.swing.JTextField();
        lblAddLine2 = new javax.swing.JLabel();
        txtAddLine2 = new javax.swing.JTextField();
        lblAddLine3 = new javax.swing.JLabel();
        txtAddLine3 = new javax.swing.JTextField();
        lblRequiredName = new javax.swing.JLabel();
        lblRequiredAddLine1 = new javax.swing.JLabel();
        lblRequiredAddLine4 = new javax.swing.JLabel();
        lblRequiredContactNumber = new javax.swing.JLabel();
        pnlItems = new javax.swing.JPanel();
        lblItems = new javax.swing.JLabel();
        cmbPizzas = new javax.swing.JComboBox<>();
        lblPizzas = new javax.swing.JLabel();
        lblDrinks = new javax.swing.JLabel();
        cmbDrinks = new javax.swing.JComboBox<>();
        rad8Inch = new javax.swing.JRadioButton();
        rad12Inch = new javax.swing.JRadioButton();
        rad16Inch = new javax.swing.JRadioButton();
        txtPizzaQuantity = new javax.swing.JTextField();
        txtDrinkQuantity = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnDisplay = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        pnlOrderSummary = new javax.swing.JPanel();
        lblOrderedItems = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOrderedItems = new javax.swing.JTextArea();
        txtTotalPrice = new javax.swing.JTextField();
        lblTotalPrice = new javax.swing.JLabel();
        pnlLogo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        mnuOrderForm = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuFile_Display = new javax.swing.JMenuItem();
        menuFile_Reset = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuHelp = new javax.swing.JMenu();
        mnuHelp_Contents = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fabulous Pizzas");
        setName("frmOrderForm"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblCustomerDetails.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblCustomerDetails.setText("Customer details");

        lblAddLine4.setText("Address Line 4 :");
        lblAddLine4.setToolTipText("");

        txtAddLine4.setToolTipText("E.g. NW2 6UP");

        lblName.setText("Name :");
        lblName.setToolTipText("");

        lblContactNumber.setText("Contact Number :");

        txtName.setToolTipText("E.g. John Smith");

        txtContactNumber.setToolTipText("E.g. 07894129742");
        txtContactNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContactNumberKeyTyped(evt);
            }
        });

        lblAddLine1.setText("Address Line 1 :");
        lblAddLine1.setToolTipText("");

        txtAddLine1.setToolTipText("E.g. 64 Zoo Lane");

        lblAddLine2.setText("Address Line 2 :");

        txtAddLine2.setToolTipText("");

        lblAddLine3.setText("Address Line 3 :");

        txtAddLine3.setToolTipText("");

        lblRequiredName.setForeground(new java.awt.Color(255, 51, 0));
        lblRequiredName.setText("(*)");
        lblRequiredName.setToolTipText("Required field");

        lblRequiredAddLine1.setForeground(new java.awt.Color(255, 51, 0));
        lblRequiredAddLine1.setText("(*)");
        lblRequiredAddLine1.setToolTipText("Required field");

        lblRequiredAddLine4.setForeground(new java.awt.Color(255, 51, 0));
        lblRequiredAddLine4.setText("(*)");
        lblRequiredAddLine4.setToolTipText("Required field");

        lblRequiredContactNumber.setForeground(new java.awt.Color(255, 51, 0));
        lblRequiredContactNumber.setText("(*)");
        lblRequiredContactNumber.setToolTipText("Required field");

        javax.swing.GroupLayout pnlCustomerDetailsLayout = new javax.swing.GroupLayout(pnlCustomerDetails);
        pnlCustomerDetails.setLayout(pnlCustomerDetailsLayout);
        pnlCustomerDetailsLayout.setHorizontalGroup(
            pnlCustomerDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCustomerDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCustomerDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCustomerDetailsLayout.createSequentialGroup()
                        .addGroup(pnlCustomerDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlCustomerDetailsLayout.createSequentialGroup()
                                .addComponent(lblContactNumber)
                                .addGap(18, 18, 18)
                                .addComponent(txtContactNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))
                            .addGroup(pnlCustomerDetailsLayout.createSequentialGroup()
                                .addGroup(pnlCustomerDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblName)
                                    .addComponent(lblAddLine1)
                                    .addComponent(lblAddLine2)
                                    .addComponent(lblAddLine3)
                                    .addComponent(lblAddLine4))
                                .addGap(23, 23, 23)
                                .addGroup(pnlCustomerDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtAddLine3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                    .addComponent(txtAddLine2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAddLine1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAddLine4))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlCustomerDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRequiredName)
                            .addComponent(lblRequiredAddLine1)
                            .addComponent(lblRequiredAddLine4)
                            .addComponent(lblRequiredContactNumber)))
                    .addComponent(lblCustomerDetails))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        pnlCustomerDetailsLayout.setVerticalGroup(
            pnlCustomerDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCustomerDetailsLayout.createSequentialGroup()
                .addComponent(lblCustomerDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(pnlCustomerDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRequiredName))
                .addGap(18, 18, 18)
                .addGroup(pnlCustomerDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddLine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddLine1)
                    .addComponent(lblRequiredAddLine1))
                .addGap(19, 19, 19)
                .addGroup(pnlCustomerDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddLine2)
                    .addComponent(txtAddLine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(pnlCustomerDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddLine3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddLine3))
                .addGap(18, 18, 18)
                .addGroup(pnlCustomerDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddLine4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddLine4)
                    .addComponent(lblRequiredAddLine4))
                .addGap(18, 18, 18)
                .addGroup(pnlCustomerDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContactNumber)
                    .addComponent(lblRequiredContactNumber))
                .addGap(12, 12, 12))
        );

        pnlItems.setToolTipText("");
        pnlItems.setName(""); // NOI18N

        lblItems.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblItems.setText("Items");
        lblItems.setToolTipText("");

        cmbPizzas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a pizza...", "Magherita", "Lusc. Vegetarian Delight", "Lusc. Spicy Sausage", "Lusc. Meat Feast", "Deadly Hot Chilli", "Lusc. Supreme" }));
        cmbPizzas.setToolTipText("");
        cmbPizzas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPizzasActionPerformed(evt);
            }
        });

        lblPizzas.setText("Pizzas :");
        lblPizzas.setToolTipText("");

        lblDrinks.setText("Drinks :");

        cmbDrinks.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a drink...", "Lusc. Cola", "Lusc. Juice" }));
        cmbDrinks.setToolTipText("");

        rad8Inch.setSelected(true);
        rad8Inch.setText("8\"");
        rad8Inch.setToolTipText("");

        rad12Inch.setText("12\"");
        rad12Inch.setToolTipText("");

        rad16Inch.setText("16\"");
        rad16Inch.setToolTipText("");

        txtPizzaQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPizzaQuantityKeyTyped(evt);
            }
        });

        txtDrinkQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDrinkQuantityKeyTyped(evt);
            }
        });

        btnAdd.setText("Add to order");
        btnAdd.setToolTipText("");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDisplay.setText("Display receipt");
        btnDisplay.setToolTipText("");
        btnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.setToolTipText("");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlItemsLayout = new javax.swing.GroupLayout(pnlItems);
        pnlItems.setLayout(pnlItemsLayout);
        pnlItemsLayout.setHorizontalGroup(
            pnlItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlItemsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlItemsLayout.createSequentialGroup()
                        .addGroup(pnlItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlItemsLayout.createSequentialGroup()
                                .addComponent(lblDrinks)
                                .addGap(18, 18, 18)
                                .addComponent(cmbDrinks, 0, 163, Short.MAX_VALUE))
                            .addComponent(lblItems)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlItemsLayout.createSequentialGroup()
                                .addComponent(lblPizzas)
                                .addGap(18, 18, 18)
                                .addComponent(cmbPizzas, 0, 1, Short.MAX_VALUE))
                            .addGroup(pnlItemsLayout.createSequentialGroup()
                                .addComponent(rad8Inch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rad12Inch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rad16Inch)))
                        .addGap(18, 18, 18)
                        .addGroup(pnlItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPizzaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDrinkQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnReset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDisplay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlItemsLayout.setVerticalGroup(
            pnlItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlItemsLayout.createSequentialGroup()
                .addComponent(lblItems)
                .addGap(24, 24, 24)
                .addGroup(pnlItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPizzas)
                    .addComponent(cmbPizzas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPizzaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rad8Inch)
                    .addComponent(rad12Inch)
                    .addComponent(rad16Inch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDrinks)
                    .addComponent(cmbDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDrinkQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDisplay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReset)
                .addContainerGap())
        );

        lblOrderedItems.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblOrderedItems.setText("Ordered items");
        lblOrderedItems.setToolTipText("");

        txtOrderedItems.setEditable(false);
        txtOrderedItems.setColumns(20);
        txtOrderedItems.setRows(5);
        txtOrderedItems.setToolTipText("");
        jScrollPane1.setViewportView(txtOrderedItems);

        txtTotalPrice.setEditable(false);
        txtTotalPrice.setToolTipText("");

        lblTotalPrice.setText("Total price :");
        lblTotalPrice.setToolTipText("Current subtotal of order");

        javax.swing.GroupLayout pnlOrderSummaryLayout = new javax.swing.GroupLayout(pnlOrderSummary);
        pnlOrderSummary.setLayout(pnlOrderSummaryLayout);
        pnlOrderSummaryLayout.setHorizontalGroup(
            pnlOrderSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrderSummaryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOrderSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlOrderSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOrderSummaryLayout.createSequentialGroup()
                            .addComponent(lblTotalPrice)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblOrderedItems))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnlOrderSummaryLayout.setVerticalGroup(
            pnlOrderSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrderSummaryLayout.createSequentialGroup()
                .addComponent(lblOrderedItems)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlOrderSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalPrice))
                .addGap(15, 15, 15))
        );

        pnlLogo.setLayout(null);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fabulous_pizzas_logo.png"))); // NOI18N
        lblLogo.setToolTipText("");
        pnlLogo.add(lblLogo);
        lblLogo.setBounds(0, 0, 150, 150);

        mnuOrderForm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mnuOrderFormKeyPressed(evt);
            }
        });

        mnuFile.setText("File");

        mnuFile_Display.setText("Display receipt");
        mnuFile_Display.setToolTipText("");
        mnuFile_Display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFile_DisplayActionPerformed(evt);
            }
        });
        mnuFile.add(mnuFile_Display);

        menuFile_Reset.setText("Reset");
        menuFile_Reset.setToolTipText("");
        menuFile_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFile_ResetActionPerformed(evt);
            }
        });
        mnuFile.add(menuFile_Reset);
        mnuFile.add(jSeparator1);

        mnuOrderForm.add(mnuFile);

        mnuHelp.setText("Help");

        mnuHelp_Contents.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        mnuHelp_Contents.setText("Help contents");
        mnuHelp_Contents.setToolTipText("");
        mnuHelp_Contents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHelp_ContentsActionPerformed(evt);
            }
        });
        mnuHelp.add(mnuHelp_Contents);

        mnuOrderForm.add(mnuHelp);

        setJMenuBar(mnuOrderForm);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlCustomerDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlOrderSummary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlCustomerDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(pnlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlOrderSummary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbPizzasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPizzasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPizzasActionPerformed

    private void mnuOrderFormKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mnuOrderFormKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuOrderFormKeyPressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        System.exit(0);        
    }//GEN-LAST:event_formWindowClosing

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        //currently selected items and the default selected items.
        String selectedPizza = cmbPizzas.getSelectedItem() + ""; 
        String defaultPizza = "Select a pizza...";
        String selectedDrink = cmbDrinks.getSelectedItem() + ""; 
        String defaultDrink = "Select a drink...";        
        
        //if neither a pizza or a drink is selected, output error
        if(selectedPizza.equals(defaultPizza) && selectedDrink.equals(defaultDrink))
        {
            JOptionPane.showMessageDialog(null, "You have not selected anything", "Error", JOptionPane.ERROR_MESSAGE);            
        }
        
        //add selected items to order, then unselected them
        orderPizza(selectedPizza, defaultPizza); orderDrink(selectedDrink, defaultDrink);
        cmbPizzas.setSelectedItem(defaultPizza); cmbDrinks.setSelectedItem(defaultDrink);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        clearFields();
    }//GEN-LAST:event_btnResetActionPerformed

    private void menuFile_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFile_ResetActionPerformed
        clearFields();
    }//GEN-LAST:event_menuFile_ResetActionPerformed

    private void btnDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayActionPerformed
        displayReceipt();
    }//GEN-LAST:event_btnDisplayActionPerformed

    private void mnuFile_DisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFile_DisplayActionPerformed
        displayReceipt();
    }//GEN-LAST:event_mnuFile_DisplayActionPerformed

    private void txtPizzaQuantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPizzaQuantityKeyTyped
        //accept numbers only
        char quantityChar = evt.getKeyChar();
        if (!(Character.isDigit(quantityChar) || (quantityChar == KeyEvent.VK_BACK_SPACE) 
            || (quantityChar == KeyEvent.VK_DELETE))) 
        {
            evt.consume();
        } 
    }//GEN-LAST:event_txtPizzaQuantityKeyTyped

    private void txtDrinkQuantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDrinkQuantityKeyTyped
        //accept numbers only
        char quantityChar = evt.getKeyChar();
        if (!(Character.isDigit(quantityChar) || (quantityChar == KeyEvent.VK_BACK_SPACE) 
            || (quantityChar == KeyEvent.VK_DELETE))) 
        {
            evt.consume();
        } 
    }//GEN-LAST:event_txtDrinkQuantityKeyTyped

    private void txtContactNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactNumberKeyTyped
        //accept numbers only
        char quantityChar = evt.getKeyChar();
        if (!(Character.isDigit(quantityChar) || (quantityChar == KeyEvent.VK_BACK_SPACE) 
            || (quantityChar == KeyEvent.VK_DELETE))) 
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtContactNumberKeyTyped

    private void mnuHelp_ContentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHelp_ContentsActionPerformed
        try 
        {
            Desktop.getDesktop().open(new java.io.File("Help.pdf"));
        } 
        catch(IOException ex) 
        {
            JOptionPane.showMessageDialog(null, "Unexpected IO error!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_mnuHelp_ContentsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderForm().setVisible(true);
            }
        });
    }
    
    //find selected pizza and determine price accordingly (calculate based on quantity), then update order and total price.
    public void orderPizza(String selectedPizza, String defaultPizza)
    {
        String[] pizzaTypes = new String[6]; double[] pizzaPricesList = new double[pizzaTypes.length];    
        createPizzas(pizzaTypes, pizzaPricesList);       
        
        if(!selectedPizza.equals(defaultPizza))
        {
            double pizzaPrice = 0;            
            for(int i=0; i<pizzaTypes.length; i++)
            {
                if(selectedPizza.equals(pizzaTypes[i]))
                {
                    pizzaPrice = pizzaPricesList[i];
                }
            }
            
            String numberInches = "8 inches";
            pizzaSizeCharge(numberInches, pizzaPrice);
            updatePizzaOrder(selectedPizza, pizzaPrice, numberInches);
        }
    }
    
    //adding the pizza types and their prices to 2 parellel arrays.
    public void createPizzas(String[] pizzaTypes, double[] pizzaPricesList)
    {
        pizzaTypes[0] = "Magherita"; 
        pizzaPricesList[0] = 7.6;
        
        pizzaTypes[1] = "Lusc. Vegetarian Delight"; 
        pizzaPricesList[1] = 8.5;
        
        pizzaTypes[2] = "Lusc. Spicy Sausage"; 
        pizzaPricesList[2] = 10.99;
        
        pizzaTypes[3] = "Lusc. Meat Feast"; 
        pizzaPricesList[3] = 10.99;
        
        pizzaTypes[4] = "Deadly Hot Chilli"; 
        pizzaPricesList[4] = 9.55;
        
        pizzaTypes[5] = "Lusc. Supreme"; 
        pizzaPricesList[5] = 12.99;
    }
    
    //account for the additional prices of 12" and 16"
    public void pizzaSizeCharge(String numberInches, double pizzaPrice)
    {
        if(rad12Inch.isSelected())
        {
            pizzaPrice += 3.99;
            numberInches = "12 inches";
        }
        else if(rad16Inch.isSelected())
        {
            pizzaPrice += 5.99;
            numberInches = "16 inches";
        }
    }
    
    //calculate price based on quantity, then add selected pizza to order and update total price.
    public void updatePizzaOrder(String selectedPizza, double pizzaPrice, String numberInches)
    {
        int pizzaQuantity = Integer.parseInt(txtPizzaQuantity.getText());
        pizzaPrice *= pizzaQuantity;
        totalPrice += pizzaPrice;        
        txtOrderedItems.append(pizzaQuantity + " x " + selectedPizza + " (" + numberInches + ") - £" + String.format("%.2f", pizzaPrice) + "\n");
        txtTotalPrice.setText("£" + String.format("%.2f", totalPrice));        
    }
    
    //find selected drink and determine price accordingly (calculate based on quantity), then update order and total price.
    public void orderDrink(String selectedDrink, String defaultDrink)
    {
        String[] drinkType = new String[2]; double[] drinkPriceList = new double[drinkType.length];
        createDrinks(drinkType, drinkPriceList);
        
        if(!selectedDrink.equals(defaultDrink))
        {
            double drinkPrice = 0;            
            for(int i=0; i<drinkType.length; i++)
            {
                if(selectedDrink.equals(drinkType[i]))
                {
                    drinkPrice = drinkPriceList[i];
                }
            }
            
            updateDrinkOrder(selectedDrink, drinkPrice);
            
        }
    }
    
    //adding the drink types and their prices to 2 parellel arrays.
    public void createDrinks(String[] drinkType, double[] drinkPriceList)
    {
        drinkType[0] = "Lusc. Cola"; drinkPriceList[0] = 1.85;
        drinkType[1] = "Lusc. Juice"; drinkPriceList[1] = 1.6;
    }
    
    //calculate price based on quantity, then update order and total price.
    public void updateDrinkOrder(String selectedDrink, double drinkPrice)
    {
        int drinkQuantity = Integer.parseInt(txtDrinkQuantity.getText());
        drinkPrice *= drinkQuantity;
        totalPrice += drinkPrice;
        txtOrderedItems.append(drinkQuantity + " x " + selectedDrink + ") - £" + String.format("%.2f", drinkPrice) + "\n");
        txtTotalPrice.setText("£" + String.format("%.2f", totalPrice));        
    }
    
    //running a series of conditions before displaying the receipt in a new form.
    public void displayReceipt()
    {
        if(txtName.getText().equals("") || txtAddLine1.getText().equals("") || 
            txtAddLine4.getText().equals("") || txtContactNumber.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "One or more fields have not been filled in!", 
                "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if(validateContactNumber(txtContactNumber.getText()) == false)
        {
            JOptionPane.showMessageDialog(null, "Please enter a valid UK phone number!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if(txtOrderedItems.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "You have not ordered any items!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            ReceiptForm receipt = new ReceiptForm();
            receipt.setVisible(true);
        }
    }
    
    //checks if the phone number starts with 0 and 7, is 11 characters and only contains characters that numbers 0-9.
    //this only works for UK numbers starting with 07.
    public boolean validateContactNumber(String num)
    {        
        return num.charAt(0) == '0' && num.charAt(1) == '7' && num.length() == 11 && num.matches("[0-9]+");
    }
    
    //clears fields or reset them to their default values.
    public void clearFields()
    {
        txtName.setText(null);
        txtAddLine1.setText(null);
        txtAddLine2.setText(null);
        txtAddLine3.setText(null);
        txtAddLine4.setText(null);
        txtContactNumber.setText(null);
        cmbPizzas.setSelectedItem("Select a pizza...");
        cmbDrinks.setSelectedItem("Select a drink...");
        txtOrderedItems.setText(null);
        txtTotalPrice.setText(null);      
        rad8Inch.setSelected(true);
        txtPizzaQuantity.setText("1"); txtDrinkQuantity.setText("1");
        totalPrice = 0;
    }
    
    //filling in values and loading receipt before compiling for testing purposes
    public void quickTesting()
    {
        txtName.setText("Saagar Shah");
        txtAddLine1.setText("64 Zoo Lane");
        txtAddLine4.setText("NW2 6UP");
        txtContactNumber.setText("07548689425");
        cmbPizzas.setSelectedItem("Magherita");        
        orderPizza("Magherita", "Select a pizza...");
        
        new ReceiptForm().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDisplay;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> cmbDrinks;
    private javax.swing.JComboBox<String> cmbPizzas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblAddLine1;
    private javax.swing.JLabel lblAddLine2;
    private javax.swing.JLabel lblAddLine3;
    private javax.swing.JLabel lblAddLine4;
    private javax.swing.JLabel lblContactNumber;
    private javax.swing.JLabel lblCustomerDetails;
    private javax.swing.JLabel lblDrinks;
    private javax.swing.JLabel lblItems;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOrderedItems;
    private javax.swing.JLabel lblPizzas;
    private javax.swing.JLabel lblRequiredAddLine1;
    private javax.swing.JLabel lblRequiredAddLine4;
    private javax.swing.JLabel lblRequiredContactNumber;
    private javax.swing.JLabel lblRequiredName;
    private javax.swing.JLabel lblTotalPrice;
    private javax.swing.JMenuItem menuFile_Reset;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenuItem mnuFile_Display;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenuItem mnuHelp_Contents;
    private javax.swing.JMenuBar mnuOrderForm;
    private javax.swing.JPanel pnlCustomerDetails;
    private javax.swing.JPanel pnlItems;
    private javax.swing.JPanel pnlLogo;
    private javax.swing.JPanel pnlOrderSummary;
    private javax.swing.JRadioButton rad12Inch;
    private javax.swing.JRadioButton rad16Inch;
    private javax.swing.JRadioButton rad8Inch;
    public static javax.swing.JTextField txtAddLine1;
    private javax.swing.JTextField txtAddLine2;
    private javax.swing.JTextField txtAddLine3;
    public static javax.swing.JTextField txtAddLine4;
    public static javax.swing.JTextField txtContactNumber;
    private javax.swing.JTextField txtDrinkQuantity;
    public static javax.swing.JTextField txtName;
    public static javax.swing.JTextArea txtOrderedItems;
    private javax.swing.JTextField txtPizzaQuantity;
    public static javax.swing.JTextField txtTotalPrice;
    // End of variables declaration//GEN-END:variables

    private void acceptNumbersOnly(KeyEvent evt) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
