
import java.awt.Desktop;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.text.*;
import java.awt.print.*;
import javafx.print.Printer;
import javax.swing.JTextArea;

public class ReceiptForm extends javax.swing.JFrame {

    public ReceiptForm() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("fabulous_pizzas_icon.png")).getImage()); //new icon
        
        String name = OrderForm.txtName.getText();
        String addLine1 = OrderForm.txtAddLine1.getText();
        String addLine4 = OrderForm.txtAddLine4.getText();
        String contactNumber = OrderForm.txtContactNumber.getText();        
        String customerDetails = name + "\n\n" + addLine1 + "\n" + addLine4 + "\n\n" + contactNumber;        
        
        txtReceipt.setText(
                    "                 FABULOUS PIZZAS \n\n" + 
                    new Date() + createLineBreak("") +
                    "Customer details: \n\n" + customerDetails + createLineBreak("") +
                    "Items ordered: \n\n" + OrderForm.txtOrderedItems.getText() + createLineBreak("") +
                    "                              Total price: " + OrderForm.txtTotalPrice.getText() 
            );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtReceipt = new javax.swing.JTextArea();
        lblOrderSummary = new javax.swing.JLabel();
        mnuReceiptForm = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuFile_Print = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuHelp = new javax.swing.JMenu();
        mnuHelp_Contents = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fabulous Pizzas");
        setName("frmReceipt"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fabulous_pizzas_logo.png"))); // NOI18N

        txtReceipt.setEditable(false);
        txtReceipt.setColumns(20);
        txtReceipt.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        txtReceipt.setRows(5);
        txtReceipt.setBorder(new javax.swing.border.MatteBorder(null));
        jScrollPane3.setViewportView(txtReceipt);

        lblOrderSummary.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblOrderSummary.setText("Order summary");

        mnuFile.setText("File");

        mnuFile_Print.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        mnuFile_Print.setText("Print receipt");
        mnuFile_Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFile_PrintActionPerformed(evt);
            }
        });
        mnuFile.add(mnuFile_Print);
        mnuFile.add(jSeparator1);

        mnuReceiptForm.add(mnuFile);

        mnuHelp.setText("Help");

        mnuHelp_Contents.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        mnuHelp_Contents.setText("Help contents");
        mnuHelp_Contents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHelp_ContentsActionPerformed(evt);
            }
        });
        mnuHelp.add(mnuHelp_Contents);

        mnuReceiptForm.add(mnuHelp);

        setJMenuBar(mnuReceiptForm);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblOrderSummary))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblOrderSummary)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_formWindowClosing

    private void mnuHelp_ContentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHelp_ContentsActionPerformed
        try 
        {
            Desktop.getDesktop().open(new java.io.File("Help.pdf"));
        } 
        catch (IOException ex) 
        {
            JOptionPane.showMessageDialog(this, "Unexpected IO error", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_mnuHelp_ContentsActionPerformed

    private void mnuFile_PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFile_PrintActionPerformed
        try
        {            
            txtReceipt.print();
        }
        //catch(java.awt.print.PrinterException e)
        catch(PrinterException e)
        {
            //System.err.format("No printer found", e.getMessage());
            JOptionPane.showMessageDialog(null, "No printer found");
        }
    }//GEN-LAST:event_mnuFile_PrintActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReceiptForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReceiptForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReceiptForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReceiptForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReceiptForm().setVisible(true);
            }
        });
    }
    
    //storing a linebreak in a variable using a loop that can be used in anything.
    public String createLineBreak(String lineBreak) {
        for (int i = 0; i < 49; i++) {
            lineBreak += "*";
        }
        return "\n\n" + lineBreak + "\n\n";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblOrderSummary;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenuItem mnuFile_Print;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenuItem mnuHelp_Contents;
    private javax.swing.JMenuBar mnuReceiptForm;
    private javax.swing.JTextArea txtReceipt;
    // End of variables declaration//GEN-END:variables
}
